@domain = http://localhost:3000
@AccessToken = {{loginToken.response.body.$.access_token}}


###
# 회원가입
# 관리자 회원
POST {{domain}}/user/signup
Content-Type: application/json

{
    "email":"test@gmail.com",
    "nickName" : "닉네임",
    "password":"Q1w2e3r4.",
    "confirmPassword":"Q1w2e3r4.",
    "role": 1
}

###
# 회원가입
# 일반 회원
POST {{domain}}/user/signup
Content-Type: application/json

{
    "email":"test22@gmail.com",
    "nickName" : "닉네임22",
    "password":"Q1w2e3r4.",
    "confirmPassword":"Q1w2e3r4.",
    "role":0
}

###
# 로그인
# 이 요청은 사용자 로그인을 처리합니다.
# @name loginToken
POST {{domain}}/user/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"Q1w2e3r4."
}

###
# 사용자 정보 조회
# 이 요청은 현재 로그인된 사용자의 정보를 조회합니다. (인증 토큰 필요)
GET {{domain}}/user
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

###
# 로그아웃
GET {{domain}}/user/logout
