@domain = http://localhost:3000
@AccessToken = {{loginToken.response.body.$.access_token}}


###
# 로그인
# 이 요청은 사용자 로그인을 처리합니다.
# @name loginToken
POST {{domain}}/user/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"Q1w2e3r4."
}


###
# 공연 등록
POST {{domain}}/show
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
    "title":"심땡땡의 토크콘서트",
    "contents" : "재단히 유명한 심땡땡씨의 인생 성공기!",
    "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfezm43b8qF3aMdXyiGYaqrJZKyN1md-HevQ&usqp=CAU",
    "location":"서울시",
    "date": [2024, 0, 12, 12, 30, 0],
    "category": 2
}


###
# 공연 조회
GET {{domain}}/show
Authorization: Bearer {{AccessToken}}
Content-Type: application/json


# ###
# # 공연 수정
# PATCH {{domain}}/show/2
# Authorization: Bearer {{AccessToken}}
# Content-Type: application/json

# {
#     "date": [2024, 1, 3, 12, 30, 0]
# }


###
# 공연 삭제
DELETE {{domain}}/show/1
Authorization: Bearer {{AccessToken}}
Content-Type: application/json
